jobs:
  build:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Pull Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./test/build

name: Build

on:
  schedule:
    - cron: "25 0/3 * * *"
